### PR TITLE
Updated locator to fix 2.8 clusterGroup failures

### PR DESCRIPTION
**Pull request by sbulage**
Fixes: #240

### CODE REVIEW

**Comment by sbulage** [comment]
Before creating this PR, I ran CI 2.8 run --> https://github.com/rancher/fleet-e2e/actions/runs/12180011742

Here is the result: 
Screenshot from 2024-12-05 21-24-18


Wait for the 2.9 and 2.10 result.

**Comment by mmartin24** [comment]
@sbulage something did not go well in the 2.10 and 2.9 ci's. I will hold the approval for the time being, ok?

**Comment by sbulage** [comment]
Above PR CI 2.9 result:

image

**Comment by sbulage** [comment]
:green_circle: CI 2.10 --> https://github.com/rancher/fleet-e2e/actions/runs/12197673770/job/34029194145

**Comment by sbulage** [comment]
CI 2.8 Run: https://github.com/rancher/fleet-e2e/actions/runs/12198751305

**Comment by sbulage** [comment]
> @sbulage something did not go well in the 2.10 and 2.9 ci's. I will hold the approval for the time being, ok?

Fixed the failing part for all versions.

**Review by mmartin24 — APPROVED** [review]
LGTM. Thanks for the adjustments.

**Pull request merged**
