### PR TITLE
Enable mochawesome reporter and change several filepaths

### PR DESCRIPTION
**Pull request by thehejik**
This was an attempt to enable uploading screenshots to qase but it is not supported in current qase reporter 1.4.1 and latest 1.4.3 (built 8 months ago) seems to be broken (upload doesn't work), plus this new version creates new qase test cases for `it` blocks where the qase id is not specified (first_login) which is not desired.

Also:
* changed location of several paths and removed the absolute paths from includes in cy tests. I think this is now closer to default cy dir tree structure and it should be better for local runs, ref. https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Folder-structure
* enabled multireporter + mochawesome reported to see failures in github logs, ref https://github.com/rancher/fleet-e2e/issues/47
*  preparation for better handling of `QASE_RUN_NAME`

Manual testrun on v2.9-head https://github.com/rancher/fleet-e2e/actions/runs/8701086745/job/23862428861

### CODE REVIEW

**Review by mmartin24 — CHANGES_REQUESTED** [review]
I'm having issues running tests locally after changes on relative paths. 
It may be only me, but executing `npx cypress open` on old path `fleet-e2e/tests/cypress` now results in creating new cypress. 
Let's pls take a look together.

**Comment by thehejik** [comment]
> I'm having issues running tests locally after changes on relative paths. It may be only me, but executing `npx cypress open` on old path `fleet-e2e/tests/cypress` now results in creating new cypress. Let's pls take a look together.

I didn't try locally, but I believe it should be executed now from `fleet-e2e/tests` as `packages.json` an `cypress.config.ts` were moved there.

**Comment by mmartin24** [comment]
As discussed offline the view shown in [ci run #127](https://github.com/rancher/fleet-e2e/actions/runs/8701190595/job/23862724178) is great:
image

if this can be applied also when it fails instead of current bulky one would be awesome

**Review by mmartin24 — APPROVED** [review]
LGTM

**Comment by thehejik** [comment]
> As discussed offline the view shown in [ci run #127](https://github.com/rancher/fleet-e2e/actions/runs/8701190595/job/23862724178) is great: image
> 
> if this can be applied also when it fails instead of current bulky one would be awesome

solved

**Comment by thehejik** [comment]
> > > I'm having issues running tests locally after changes on relative paths. It may be only me, but executing `npx cypress open` on old path `fleet-e2e/tests/cypress` now results in creating new cypress. Let's pls take a look together.
> > 
> > 
> > I didn't try locally, but I believe it should be executed now from `fleet-e2e/tests` as `packages.json` an `cypress.config.ts` were moved there.
> 
> Sorry but unfortunately still does not work for me
> 
> ```
> ➜  tests git:(screen-mocha) npx cypress run --env grepTags="@p0 @p1" --spec "e2e/unit_tests/*.spec.ts"
> Your configFile at /home/mmartin/suse/suse-repos/fleet-e2e/tests/cypress.config.ts set an invalid value:
> ```

you have to re-run `npm install` from `fleet-e2e/tests` instead of `fleet-e2e/tests/cypress` + same for `npx cypress run`.

I was using this command:
```bash
cd fleet-e2e/tests
RANCHER_URL=https://myrancher/dashboard \
RANCHER_USER=admin \
RANCHER_PASSWORD=mypassword \
npx cypress run \
--config-file=cypress.config.ts --spec cypress/e2e/unit_tests/first_login_rancher.spec.ts
```

**Pull request merged**
